# Generated by Django 5.0 on 2023-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='ABC 1234', max_length=10),
            preserve_default=False,
        ),
    ]
