# Generated by Django 5.0 on 2023-12-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date']},
        ),
    ]
