# Generated by Django 5.0 on 2023-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Recitation', 'Recitation')], default=['Lecture'], max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'format')},
        ),
    ]
