# Generated by Django 4.1.7 on 2023-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_is_complete_assignment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Recitation', 'Recitation')], default='Lecture', max_length=12),
        ),
    ]
